In [37]:
# load and summarize the dataset
from pandas import read_csv
import numpy as np
import pandas as pd
df = read_csv('mtcars.csv')
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [2]:
df.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [3]:
len(df.columns)

12

In [4]:
df.shape

(32, 12)

In [33]:
type(df)

pandas.core.frame.DataFrame

In [87]:
data = df.drop('model',axis='columns')

In [88]:
data

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

# Now i am going to using z-scores method for finding the outlier

In [89]:
from scipy import stats

In [95]:
x = np.abs(stats.zscore(data))

In [91]:
x.shape

(32, 11)

In [92]:
x

array([[1.53299135e-01, 1.06667720e-01, 5.79750316e-01, 5.43654869e-01,
        5.76594481e-01, 6.20166581e-01, 7.89600577e-01, 8.81917104e-01,
        1.20894105e+00, 4.30331483e-01, 7.46967077e-01],
       [1.53299135e-01, 1.06667720e-01, 5.79750316e-01, 5.43654869e-01,
        5.76594481e-01, 3.55382189e-01, 4.71201785e-01, 8.81917104e-01,
        1.20894105e+00, 4.30331483e-01, 7.46967077e-01],
       [4.56736599e-01, 1.24445674e+00, 1.00602601e+00, 7.95569902e-01,
        4.81584062e-01, 9.31677630e-01, 4.32823359e-01, 1.13389342e+00,
        1.20894105e+00, 4.30331483e-01, 1.14010764e+00],
       [2.20729683e-01, 1.06667720e-01, 2.23615417e-01, 5.43654869e-01,
        9.81576392e-01, 2.33633287e-03, 9.04735855e-01, 1.13389342e+00,
        8.27170192e-01, 9.46729262e-01, 1.14010764e+00],
       [2.34426513e-01, 1.03112130e+00, 1.05977159e+00, 4.19549669e-01,
        8.48561806e-01, 2.31296954e-01, 4.71201785e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 5.11082737e-01],
       [3.35572334e-01, 1.06667720e-01, 4.69056970e-02, 6.17747526e-01,
        1.58964307e+00, 2.52064357e-01, 1.34821989e+00, 1.13389342e+00,
        8.27170192e-01, 9.46729262e-01, 1.14010764e+00],
       [9.76162534e-01, 1.03112130e+00, 1.05977159e+00, 1.45684686e+00,
        7.34549303e-01, 3.66285076e-01, 1.14211353e+00, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 7.46967077e-01],
       [7.26458788e-01, 1.24445674e+00, 6.88778522e-01, 1.25494437e+00,
        1.77550721e-01, 2.82955870e-02, 1.22313465e+00, 1.13389342e+00,
        8.27170192e-01, 4.30331483e-01, 5.11082737e-01],
       [4.56736599e-01, 1.24445674e+00, 7.37144418e-01, 7.65932839e-01,
        6.14598649e-01, 6.98303936e-02, 2.87198554e+00, 1.13389342e+00,
        8.27170192e-01, 4.30331483e-01, 5.11082737e-01],
       [1.50138328e-01, 1.06667720e-01, 5.17448483e-01, 3.51013961e-01,
        6.14598649e-01, 2.31296954e-01, 2.56566884e-01, 1.13389342e+00,
        8.27170192e-01, 4.30331483e-01, 7.46967077e-01],
       [3.86145244e-01, 1.06667720e-01, 5.17448483e-01, 3.51013961e-01,
        6.14598649e-01, 2.31296954e-01, 5.97708448e-01, 1.13389342e+00,
        8.27170192e-01, 4.30331483e-01, 7.46967077e-01],
       [6.22152160e-01, 1.03112130e+00, 3.69532866e-01, 4.93642326e-01,
        1.00057848e+00, 8.85470158e-01, 2.55145461e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 1.17942170e-01],
       [4.70433428e-01, 1.03112130e+00, 3.69532866e-01, 4.93642326e-01,
        1.00057848e+00, 5.32424302e-01, 1.41431607e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 1.17942170e-01],
       [8.24443802e-01, 1.03112130e+00, 3.69532866e-01, 4.93642326e-01,
        1.00057848e+00, 5.84342810e-01, 8.59961025e-02, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 1.17942170e-01],
       [1.63361037e+00, 1.03112130e+00, 1.97790385e+00, 8.64105609e-01,
        1.26660765e+00, 2.11074695e+00, 7.46247170e-02, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 7.46967077e-01],
       [1.63361037e+00, 1.03112130e+00, 1.87953254e+00, 1.01229092e+00,
        1.13359306e+00, 2.29142336e+00, 1.63463666e-02, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 7.46967077e-01],
       [9.08731987e-01, 1.03112130e+00, 1.71558035e+00, 1.23456889e+00,
        6.96545135e-01, 2.20939212e+00, 2.43774076e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 7.46967077e-01],
       [2.07506974e+00, 1.24445674e+00, 1.24621597e+00, 1.19567025e+00,
        9.18631990e-01, 1.05628205e+00, 9.21792933e-01, 1.13389342e+00,
        1.20894105e+00, 4.30331483e-01, 1.14010764e+00],
       [1.73791700e+00, 1.24445674e+00, 1.27080880e+00, 1.40312969e+00,
        2.53380911e+00, 1.66372860e+00, 3.81652124e-01, 1.13389342e+00,
        1.20894105e+00, 4.30331483e-01, 5.11082737e-01],
       [2.32793429e+00, 1.24445674e+00, 1.30851780e+00, 1.21048878e+00,
        1.18466116e+00, 1.43528716e+00, 1.16627772e+00, 1.13389342e+00,
        1.20894105e+00, 4.30331483e-01, 1.14010764e+00],
       [2.37587319e-01, 1.24445674e+00, 9.06834935e-01, 7.36295776e-01,
        1.96552805e-01, 7.81113956e-01, 1.22882034e+00, 1.13389342e+00,
        8.27170192e-01, 9.46729262e-01, 1.14010764e+00],
       [7.73870892e-01, 1.03112130e+00, 7.15471988e-01, 4.90863851e-02,
        1.58964307e+00, 3.14366567e-01, 5.56487176e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 5.11082737e-01],
       [8.24443802e-01, 1.03112130e+00, 6.00705455e-01, 4.90863851e-02,
        8.48561806e-01, 2.26105103e-01, 3.12002388e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 5.11082737e-01],
       [1.14473890e+00, 1.03112130e+00, 9.77795493e-01, 1.45684686e+00,
        2.53559056e-01, 6.46645020e-01, 1.38659831e+00, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 7.46967077e-01],
       [1.50138328e-01, 1.03112130e+00, 1.38767597e+00, 4.19549669e-01,
        9.81576392e-01, 6.51836871e-01, 4.54144707e-01, 8.81917104e-01,
        8.27170192e-01, 9.46729262e-01, 5.11082737e-01],
       [1.21533026e+00, 1.24445674e+00, 1.24375669e+00, 1.19567025e+00,
        9.18631990e-01, 1.33145014e+00, 5.97708448e-01, 1.13389342e+00,
        1.20894105e+00, 4.30331483e-01, 1.14010764e+00],
       [9.96180978e-01, 1.24445674e+00, 9.05195413e-01, 8.25206964e-01,
        1.58370492e+00, 1.11858426e+00, 6.53143952e-01, 8.81917104e-01,
        1.20894105e+00, 1.80739223e+00, 5.11082737e-01],
       [1.73791700e+00, 1.24445674e+00, 1.11177517e+00, 4.99199275e-01,
        3.29567391e-01, 1.76964235e+00, 5.39430097e-01, 1.13389342e+00,
        1.20894105e+00, 1.80739223e+00, 5.11082737e-01],
       [7.23297981e-01, 1.03112130e+00, 9.85993102e-01, 1.73839896e+00,
        1.18466116e+00, 4.90629903e-02, 1.90399635e+00, 8.81917104e-01,
        1.20894105e+00, 1.80739223e+00, 7.46967077e-01],
       [6.58501440e-02, 1.06667720e-01, 7.02714458e-01, 4.19549669e-01,
        4.45361340e-02, 4.64411056e-01, 1.33542708e+00, 8.81917104e-01,
        1.20894105e+00, 1.80739223e+00, 2.00501689e+00],
       [8.58159076e-01, 1.03112130e+00, 5.76112626e-01, 2.79051468e+00,
        1.07480537e-01, 3.66285076e-01, 1.84713942e+00, 8.81917104e-01,
        1.20894105e+00, 1.80739223e+00, 3.26306671e+00],
       [2.20729683e-01, 1.24445674e+00, 8.99457087e-01, 5.58473400e-01,
        9.75638241e-01, 4.54027354e-01, 4.27137666e-01, 1.13389342e+00,
        1.20894105e+00, 4.30331483e-01, 5.11082737e-01]])

In [96]:
np.where(x > 3)

(array([30], dtype=int64), array([10], dtype=int64))

2nd Question answer

In [8]:
from sklearn.datasets import load_boston
import pandas as pd

In [9]:
boston = load_boston()
columns = boston.feature_names
columns

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [10]:
#create the dataframe
boston_df = pd.DataFrame(boston.data)
boston_df.columns = columns
boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [54]:
type(boston_df)

pandas.core.frame.DataFrame

In [13]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(boston_df))
print(z)

[[0.41978194 0.28482986 1.2879095  ... 1.45900038 0.44105193 1.0755623 ]
 [0.41733926 0.48772236 0.59338101 ... 0.30309415 0.44105193 0.49243937]
 [0.41734159 0.48772236 0.59338101 ... 0.30309415 0.39642699 1.2087274 ]
 ...
 [0.41344658 0.48772236 0.11573841 ... 1.17646583 0.44105193 0.98304761]
 [0.40776407 0.48772236 0.11573841 ... 1.17646583 0.4032249  0.86530163]
 [0.41500016 0.48772236 0.11573841 ... 1.17646583 0.44105193 0.66905833]]

In [62]:
z.shape

(506, 13)

In [70]:
threshold = 3
print(np.where(z > 3))

(array([ 55,  56,  57, 102, 141, 142, 152, 154, 155, 160, 162, 163, 199,
       200, 201, 202, 203, 204, 208, 209, 210, 211, 212, 216, 218, 219,
       220, 221, 222, 225, 234, 236, 256, 257, 262, 269, 273, 274, 276,
       277, 282, 283, 283, 284, 347, 351, 352, 353, 353, 354, 355, 356,
       357, 358, 363, 364, 364, 365, 367, 369, 370, 372, 373, 374, 374,
       380, 398, 404, 405, 406, 410, 410, 411, 412, 412, 414, 414, 415,
       416, 418, 418, 419, 423, 424, 425, 426, 427, 427, 429, 431, 436,
       437, 438, 445, 450, 454, 455, 456, 457, 466], dtype=int64), array([ 1,  1,  1, 11, 12,  3,  3,  3,  3,  3,  3,  3,  1,  1,  1,  1,  1,
        1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  5,  3,  3,  1,  5,
        5,  3,  3,  3,  3,  3,  3,  1,  3,  1,  1,  7,  7,  1,  7,  7,  7,
        3,  3,  3,  3,  3,  5,  5,  5,  3,  3,  3, 12,  5, 12,  0,  0,  0,
        0,  5,  0, 11, 11, 11, 12,  0, 12, 11, 11,  0, 11, 11, 11, 11, 11,
       11,  0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
      dtype=int64))